services:
  piston:
    image: ghcr.io/engineer-man/piston
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - ./temp/piston/packages:/piston/packages
    tmpfs:
      - /tmp:exec

  db:
    image: postgres:17.5
    env_file: .env
    ports:
      - "5432:5432"