services:
  localbox:
    image: ghcr.io/thecomputerm/localbox:latest
    cgroup: host
    privileged: true
    ports:
      - "2000:2000"
    tmpfs:
      - /tmp:exec

  db:
    image: postgres:17.5
    env_file: .env
    ports:
      - "5432:5432"