/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminParticipantRouteImport } from './routes/admin/participant'
import { Route as AdminLanguagesRouteImport } from './routes/admin/languages'
import { Route as AdminConfigurationRouteImport } from './routes/admin/configuration'
import { Route as AdminContestIndexRouteImport } from './routes/admin/contest/index'
import { Route as AppContestIdRouteImport } from './routes/app/contest/$id'
import { Route as AdminContestNewRouteImport } from './routes/admin/contest/new'
import { Route as AdminContestIdRouteImport } from './routes/admin/contest/$id'
import { Route as AdminContestIdIndexRouteImport } from './routes/admin/contest/$id/index'
import { Route as AppContestIdSubmissionsRouteImport } from './routes/app/contest/$id/submissions'
import { Route as AppContestIdProblemRouteImport } from './routes/app/contest/$id/problem'
import { Route as AppContestIdLeaderboardRouteImport } from './routes/app/contest/$id/leaderboard'
import { Route as AppContestIdProblemIndexRouteImport } from './routes/app/contest/$id/problem/index'
import { Route as AdminContestIdProblemIndexRouteImport } from './routes/admin/contest/$id/problem/index'
import { Route as AppContestIdProblemNumberRouteImport } from './routes/app/contest/$id/problem/$number'
import { Route as AdminContestIdProblemProblemRouteImport } from './routes/admin/contest/$id/problem/$problem'
import { ServerRoute as ApiSplatServerRouteImport } from './routes/api/$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantRoute = AdminParticipantRouteImport.update({
  id: '/participant',
  path: '/participant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigurationRoute = AdminConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestIndexRoute = AdminContestIndexRouteImport.update({
  id: '/contest/',
  path: '/contest/',
  getParentRoute: () => AdminRoute,
} as any)
const AppContestIdRoute = AppContestIdRouteImport.update({
  id: '/contest/$id',
  path: '/contest/$id',
  getParentRoute: () => AppRoute,
} as any)
const AdminContestNewRoute = AdminContestNewRouteImport.update({
  id: '/contest/new',
  path: '/contest/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestIdRoute = AdminContestIdRouteImport.update({
  id: '/contest/$id',
  path: '/contest/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestIdIndexRoute = AdminContestIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContestIdRoute,
} as any)
const AppContestIdSubmissionsRoute = AppContestIdSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppContestIdRoute,
} as any)
const AppContestIdProblemRoute = AppContestIdProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => AppContestIdRoute,
} as any)
const AppContestIdLeaderboardRoute = AppContestIdLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppContestIdRoute,
} as any)
const AppContestIdProblemIndexRoute =
  AppContestIdProblemIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppContestIdProblemRoute,
  } as any)
const AdminContestIdProblemIndexRoute =
  AdminContestIdProblemIndexRouteImport.update({
    id: '/problem/',
    path: '/problem/',
    getParentRoute: () => AdminContestIdRoute,
  } as any)
const AppContestIdProblemNumberRoute =
  AppContestIdProblemNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => AppContestIdProblemRoute,
  } as any)
const AdminContestIdProblemProblemRoute =
  AdminContestIdProblemProblemRouteImport.update({
    id: '/problem/$problem',
    path: '/problem/$problem',
    getParentRoute: () => AdminContestIdRoute,
  } as any)
const ApiSplatServerRoute = ApiSplatServerRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/participant': typeof AdminParticipantRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/contest/$id': typeof AdminContestIdRouteWithChildren
  '/admin/contest/new': typeof AdminContestNewRoute
  '/app/contest/$id': typeof AppContestIdRouteWithChildren
  '/admin/contest': typeof AdminContestIndexRoute
  '/app/contest/$id/leaderboard': typeof AppContestIdLeaderboardRoute
  '/app/contest/$id/problem': typeof AppContestIdProblemRouteWithChildren
  '/app/contest/$id/submissions': typeof AppContestIdSubmissionsRoute
  '/admin/contest/$id/': typeof AdminContestIdIndexRoute
  '/admin/contest/$id/problem/$problem': typeof AdminContestIdProblemProblemRoute
  '/app/contest/$id/problem/$number': typeof AppContestIdProblemNumberRoute
  '/admin/contest/$id/problem': typeof AdminContestIdProblemIndexRoute
  '/app/contest/$id/problem/': typeof AppContestIdProblemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/participant': typeof AdminParticipantRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/contest/new': typeof AdminContestNewRoute
  '/app/contest/$id': typeof AppContestIdRouteWithChildren
  '/admin/contest': typeof AdminContestIndexRoute
  '/app/contest/$id/leaderboard': typeof AppContestIdLeaderboardRoute
  '/app/contest/$id/submissions': typeof AppContestIdSubmissionsRoute
  '/admin/contest/$id': typeof AdminContestIdIndexRoute
  '/admin/contest/$id/problem/$problem': typeof AdminContestIdProblemProblemRoute
  '/app/contest/$id/problem/$number': typeof AppContestIdProblemNumberRoute
  '/admin/contest/$id/problem': typeof AdminContestIdProblemIndexRoute
  '/app/contest/$id/problem': typeof AppContestIdProblemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/participant': typeof AdminParticipantRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/contest/$id': typeof AdminContestIdRouteWithChildren
  '/admin/contest/new': typeof AdminContestNewRoute
  '/app/contest/$id': typeof AppContestIdRouteWithChildren
  '/admin/contest/': typeof AdminContestIndexRoute
  '/app/contest/$id/leaderboard': typeof AppContestIdLeaderboardRoute
  '/app/contest/$id/problem': typeof AppContestIdProblemRouteWithChildren
  '/app/contest/$id/submissions': typeof AppContestIdSubmissionsRoute
  '/admin/contest/$id/': typeof AdminContestIdIndexRoute
  '/admin/contest/$id/problem/$problem': typeof AdminContestIdProblemProblemRoute
  '/app/contest/$id/problem/$number': typeof AppContestIdProblemNumberRoute
  '/admin/contest/$id/problem/': typeof AdminContestIdProblemIndexRoute
  '/app/contest/$id/problem/': typeof AppContestIdProblemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/configuration'
    | '/admin/languages'
    | '/admin/participant'
    | '/admin/'
    | '/app/'
    | '/admin/contest/$id'
    | '/admin/contest/new'
    | '/app/contest/$id'
    | '/admin/contest'
    | '/app/contest/$id/leaderboard'
    | '/app/contest/$id/problem'
    | '/app/contest/$id/submissions'
    | '/admin/contest/$id/'
    | '/admin/contest/$id/problem/$problem'
    | '/app/contest/$id/problem/$number'
    | '/admin/contest/$id/problem'
    | '/app/contest/$id/problem/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/configuration'
    | '/admin/languages'
    | '/admin/participant'
    | '/admin'
    | '/app'
    | '/admin/contest/new'
    | '/app/contest/$id'
    | '/admin/contest'
    | '/app/contest/$id/leaderboard'
    | '/app/contest/$id/submissions'
    | '/admin/contest/$id'
    | '/admin/contest/$id/problem/$problem'
    | '/app/contest/$id/problem/$number'
    | '/admin/contest/$id/problem'
    | '/app/contest/$id/problem'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/configuration'
    | '/admin/languages'
    | '/admin/participant'
    | '/admin/'
    | '/app/'
    | '/admin/contest/$id'
    | '/admin/contest/new'
    | '/app/contest/$id'
    | '/admin/contest/'
    | '/app/contest/$id/leaderboard'
    | '/app/contest/$id/problem'
    | '/app/contest/$id/submissions'
    | '/admin/contest/$id/'
    | '/admin/contest/$id/problem/$problem'
    | '/app/contest/$id/problem/$number'
    | '/admin/contest/$id/problem/'
    | '/app/contest/$id/problem/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}
export interface FileServerRoutesByFullPath {
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/$': typeof ApiSplatServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/$' | '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/$' | '/api/auth/$'
  id: '__root__' | '/api/$' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSplatServerRoute: typeof ApiSplatServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participant': {
      id: '/admin/participant'
      path: '/participant'
      fullPath: '/admin/participant'
      preLoaderRoute: typeof AdminParticipantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuration': {
      id: '/admin/configuration'
      path: '/configuration'
      fullPath: '/admin/configuration'
      preLoaderRoute: typeof AdminConfigurationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contest/': {
      id: '/admin/contest/'
      path: '/contest'
      fullPath: '/admin/contest'
      preLoaderRoute: typeof AdminContestIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/contest/$id': {
      id: '/app/contest/$id'
      path: '/contest/$id'
      fullPath: '/app/contest/$id'
      preLoaderRoute: typeof AppContestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/contest/new': {
      id: '/admin/contest/new'
      path: '/contest/new'
      fullPath: '/admin/contest/new'
      preLoaderRoute: typeof AdminContestNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contest/$id': {
      id: '/admin/contest/$id'
      path: '/contest/$id'
      fullPath: '/admin/contest/$id'
      preLoaderRoute: typeof AdminContestIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contest/$id/': {
      id: '/admin/contest/$id/'
      path: '/'
      fullPath: '/admin/contest/$id/'
      preLoaderRoute: typeof AdminContestIdIndexRouteImport
      parentRoute: typeof AdminContestIdRoute
    }
    '/app/contest/$id/submissions': {
      id: '/app/contest/$id/submissions'
      path: '/submissions'
      fullPath: '/app/contest/$id/submissions'
      preLoaderRoute: typeof AppContestIdSubmissionsRouteImport
      parentRoute: typeof AppContestIdRoute
    }
    '/app/contest/$id/problem': {
      id: '/app/contest/$id/problem'
      path: '/problem'
      fullPath: '/app/contest/$id/problem'
      preLoaderRoute: typeof AppContestIdProblemRouteImport
      parentRoute: typeof AppContestIdRoute
    }
    '/app/contest/$id/leaderboard': {
      id: '/app/contest/$id/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/contest/$id/leaderboard'
      preLoaderRoute: typeof AppContestIdLeaderboardRouteImport
      parentRoute: typeof AppContestIdRoute
    }
    '/app/contest/$id/problem/': {
      id: '/app/contest/$id/problem/'
      path: '/'
      fullPath: '/app/contest/$id/problem/'
      preLoaderRoute: typeof AppContestIdProblemIndexRouteImport
      parentRoute: typeof AppContestIdProblemRoute
    }
    '/admin/contest/$id/problem/': {
      id: '/admin/contest/$id/problem/'
      path: '/problem'
      fullPath: '/admin/contest/$id/problem'
      preLoaderRoute: typeof AdminContestIdProblemIndexRouteImport
      parentRoute: typeof AdminContestIdRoute
    }
    '/app/contest/$id/problem/$number': {
      id: '/app/contest/$id/problem/$number'
      path: '/$number'
      fullPath: '/app/contest/$id/problem/$number'
      preLoaderRoute: typeof AppContestIdProblemNumberRouteImport
      parentRoute: typeof AppContestIdProblemRoute
    }
    '/admin/contest/$id/problem/$problem': {
      id: '/admin/contest/$id/problem/$problem'
      path: '/problem/$problem'
      fullPath: '/admin/contest/$id/problem/$problem'
      preLoaderRoute: typeof AdminContestIdProblemProblemRouteImport
      parentRoute: typeof AdminContestIdRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AdminContestIdRouteChildren {
  AdminContestIdIndexRoute: typeof AdminContestIdIndexRoute
  AdminContestIdProblemProblemRoute: typeof AdminContestIdProblemProblemRoute
  AdminContestIdProblemIndexRoute: typeof AdminContestIdProblemIndexRoute
}

const AdminContestIdRouteChildren: AdminContestIdRouteChildren = {
  AdminContestIdIndexRoute: AdminContestIdIndexRoute,
  AdminContestIdProblemProblemRoute: AdminContestIdProblemProblemRoute,
  AdminContestIdProblemIndexRoute: AdminContestIdProblemIndexRoute,
}

const AdminContestIdRouteWithChildren = AdminContestIdRoute._addFileChildren(
  AdminContestIdRouteChildren,
)

interface AdminRouteChildren {
  AdminConfigurationRoute: typeof AdminConfigurationRoute
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  AdminParticipantRoute: typeof AdminParticipantRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContestIdRoute: typeof AdminContestIdRouteWithChildren
  AdminContestNewRoute: typeof AdminContestNewRoute
  AdminContestIndexRoute: typeof AdminContestIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfigurationRoute: AdminConfigurationRoute,
  AdminLanguagesRoute: AdminLanguagesRoute,
  AdminParticipantRoute: AdminParticipantRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContestIdRoute: AdminContestIdRouteWithChildren,
  AdminContestNewRoute: AdminContestNewRoute,
  AdminContestIndexRoute: AdminContestIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppContestIdProblemRouteChildren {
  AppContestIdProblemNumberRoute: typeof AppContestIdProblemNumberRoute
  AppContestIdProblemIndexRoute: typeof AppContestIdProblemIndexRoute
}

const AppContestIdProblemRouteChildren: AppContestIdProblemRouteChildren = {
  AppContestIdProblemNumberRoute: AppContestIdProblemNumberRoute,
  AppContestIdProblemIndexRoute: AppContestIdProblemIndexRoute,
}

const AppContestIdProblemRouteWithChildren =
  AppContestIdProblemRoute._addFileChildren(AppContestIdProblemRouteChildren)

interface AppContestIdRouteChildren {
  AppContestIdLeaderboardRoute: typeof AppContestIdLeaderboardRoute
  AppContestIdProblemRoute: typeof AppContestIdProblemRouteWithChildren
  AppContestIdSubmissionsRoute: typeof AppContestIdSubmissionsRoute
}

const AppContestIdRouteChildren: AppContestIdRouteChildren = {
  AppContestIdLeaderboardRoute: AppContestIdLeaderboardRoute,
  AppContestIdProblemRoute: AppContestIdProblemRouteWithChildren,
  AppContestIdSubmissionsRoute: AppContestIdSubmissionsRoute,
}

const AppContestIdRouteWithChildren = AppContestIdRoute._addFileChildren(
  AppContestIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppContestIdRoute: typeof AppContestIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppContestIdRoute: AppContestIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSplatServerRoute: ApiSplatServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
